name: Release

on:
    workflow_dispatch:
    release:
     types: [published]
    push:
      branches:
        - "master"
        - "22.04"
      paths:
        - "image/Dockerfile"
jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci-skip]')"
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            
          - name: Prepare
            id: prep
            run: |
              DOCKER_IMAGE="${{ secrets.DOCKER_REPOSITORY_LOCAL }}"
              GIT_BRANCH=${GITHUB_REF##*/}
              # Set the platforms to build for here and thus reduce duplicating it.
              PLATFORMS=amd64
              TAGS="${DOCKER_IMAGE}:${GIT_BRANCH}, ghcr.io/${{ github.repository_owner }}/phusion-baseimage:${GIT_BRANCH}"
              
              # Set output parameters.
              
              if [ "${{github.event_name}}" == "pull_request" ]; then
                echo ::set-output name=push::false
              else
                echo ::set-output name=push::true
                echo ::set-output name=tags::${TAGS}
                echo ::set-output name=branch::${GIT_BRANCH}
                echo ::set-output name=docker_image::${DOCKER_IMAGE}
              fi
              echo ::set-output name=platforms::${PLATFORMS}
              
          - name: Login to GHCR (Github Container Registry)
            uses: docker/login-action@v2
            if: github.event_name != 'pull_request'
            with:
             registry: ghcr.io
             username: ${{ github.actor }}
             password: ${{ secrets.GITHUB_TOKEN }}

          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v2
            with:
              install: true
              version: latest
              driver-opts: image=moby/buildkit:latest

          - name: Login to Docker Hub
            if: github.event_name != 'pull_request'
            uses: docker/login-action@v2
            with:
              registry: ${{ secrets.DOCKER_REPOSITORY }}
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              
          - name: Build and Push
            uses: docker/build-push-action@v6
            with:
              builder: ${{ steps.buildx.outputs.name }}
              context: image
              platforms: ${{ steps.prep.outputs.platforms }}
              push: ${{ steps.prep.outputs.push }}
              tags: ${{ steps.prep.outputs.tags }}
